Hw 4 daria dobrycheva
YuriiKhomych/ITEA_course pull request #33
Opened 2019-08-09 20:36 UTC by Dobrycheva

2019-08-17 14:25 UTC, YuriiKhomych requested changes

2019-08-17 14:25 UTC, YuriiKhomych commented on Daria_Dobrycheva/2_data_types/practise/HW_4_1.py
> +sample = input("somthing") #sample string
```digits = 0
alpha = 0

digits = digits + 1
digits += 1

```

2019-08-17 14:26 UTC, YuriiKhomych commented on Daria_Dobrycheva/2_data_types/practise/HW_4_1.py
> +sample = input("somthing") #sample string
Переробиш це в цьому PR чи новий створиш?

2019-08-17 14:27 UTC, Dobrycheva commented
Я жороблю і перероблю домашку і вишлю з понеділка

сб, 17 авг. 2019 г., 17:26 Yurii <notifications@github.com>:

> *@YuriiKhomych* commented on this pull request.
> ------------------------------
>
> In Daria_Dobrycheva/2_data_types/practise/HW_4_1.py
> <https://github.com/YuriiKhomych/ITEA_course/pull/33#discussion_r314948822>
> :
>
> > @@ -0,0 +1,9 @@
>
> +sample = input("somthing") #sample string
>
>
> Переробиш це в цьому PR чи новий створиш?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/YuriiKhomych/ITEA_course/pull/33?email_source=notifications&email_token=AINRTRAQLNRAWC2HQVQK7WTQFADATA5CNFSM4IKXFXQKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCB3REWQ#discussion_r314948822>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AINRTRHYQ5V7WCR2YWZJYH3QFADATANCNFSM4IKXFXQA>
> .
>

2019-08-17 14:30 UTC, YuriiKhomych commented
ок

2019-08-31 10:46 UTC, YuriiKhomych approved these changes

2019-08-31 10:46 UTC, merged