Modify gitignore, add 5th homework and practise files, add pytest for all…
YuriiKhomych/ITEA_course pull request #38
Opened 2019-08-13 12:56 UTC by VsevolodSavchenko

… exercises

2019-08-17 14:35 UTC, YuriiKhomych requested changes

2019-08-17 14:35 UTC, YuriiKhomych commented on VsevolodSavchenko/5_functions/practise/ex5.py
> +    return x == a[0] or is_member(x, a[1:])
круто)
сам робив?)

2019-08-17 14:35 UTC, YuriiKhomych commented on VsevolodSavchenko/5_functions/py_test.py
> +from hw.HW import max_in_list as my_max_list
перемісти всі імпорти на верх файлу, бо так дуже заплутано код виглядає

2019-08-17 14:35 UTC, YuriiKhomych commented on VsevolodSavchenko/5_functions/py_test.py
> +from hw.HW import max_in_list as my_max_list
тести вийшло запустити через `pytest`?

2019-08-27 16:06 UTC, VsevolodSavchenko commented on VsevolodSavchenko/5_functions/practise/ex5.py
> +    return x == a[0] or is_member(x, a[1:])
при наличии google, я богоподобен!

2019-08-27 16:06 UTC, VsevolodSavchenko commented on VsevolodSavchenko/5_functions/py_test.py
> +from hw.HW import max_in_list as my_max_list
тесты прошли норм

2019-08-28 09:37 UTC, VsevolodSavchenko commented on VsevolodSavchenko/5_functions/py_test.py
> +from hw.HW import max_in_list as my_max_list
переместил импорты

2019-08-31 10:54 UTC, YuriiKhomych approved these changes

2019-08-31 10:54 UTC, merged