Add 6 practise and homework
YuriiKhomych/ITEA_course pull request #45
Opened 2019-08-17 06:57 UTC by VsevolodSavchenko

2019-08-18 12:26 UTC, YuriiKhomych requested changes
А тести під ці всі функції напишеш?)

2019-08-18 12:26 UTC, YuriiKhomych commented on VsevolodSavchenko/6_strings/hw/hw2.py
> +    return max(map(len, words))
сам робив)?

2019-08-28 11:16 UTC, VsevolodSavchenko commented on VsevolodSavchenko/6_strings/hw/hw2.py
> +    return max(map(len, words))
дбавил

2019-08-31 11:00 UTC, YuriiKhomych approved these changes

2019-08-31 11:00 UTC, merged