Add 9th hw
YuriiKhomych/ITEA_course pull request #62
Opened 2019-09-09 11:19 UTC by VsevolodSavchenko

2019-09-09 17:30 UTC, YuriiKhomych requested changes
а взагалі все 🔥

2019-09-09 17:30 UTC, YuriiKhomych commented on VsevolodSavchenko/9_functional_programming/hw/hw3.py
> +def make_3sg_form(verb):
ти замість того щоб копіювати сюди функції можеш імпортнути декоратор в інші свої файли дз-шок і там задекорувати свої функції)

2019-09-11 12:41 UTC, VsevolodSavchenko commented on VsevolodSavchenko/9_functional_programming/hw/hw3.py
> +def make_3sg_form(verb):
Done

2019-09-11 12:47 UTC, YuriiKhomych approved these changes

2019-09-11 12:47 UTC, YuriiKhomych commented
Класс)

2019-09-11 12:47 UTC, merged